name: Bug Report
description: Create a report to help us improve
title: "Bug: "
labels: ["bug", "potential-bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please read the [FAQ](https://www.circl.lu/doc/misp/faq/) before opening an issue.

        If you would like to report a bug, please fill the template bellow:
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please be as thorough as possible.
    validations:
      required: true
  - type: input
    id: misp-version
    attributes:
      label: Version
      description: What version of MISP are you running?
      placeholder: "2.4.151"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Ubuntu, RedHat, CentOS ..."
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System version
      placeholder: "20.04"
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP version
      placeholder: "7.0, 7.1, 7.4 ..."
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you seeing the problem on?
      placeholder: "Firefox, Chrome, Safari ..."
  - type: input
    id: browser-version
    attributes:
      label: Browser version
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: extra-attachments
    attributes:
      label: Extra attachments
      description: Please add any other relevant attachments such as screenshots, log files, etc. here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/MISP/MISP/blob/2.4/code_of_conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
