blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/MISP/MISP/discussions
    about: For more general questions or ongoing debates.
  - name: FAQ
    url: https://www.circl.lu/doc/misp/faq/
    about: Please find our Frequently Asked Questions here.
  - name: Community Support
    url: https://gitter.im/MISP/Support
    about: For Community Support reach out here.
