name: Support Request
description: Support requests for MISP
title: "Support: "
labels: ["support", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Please consider the following notes
        - Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
        - Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
        - For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

        The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
        Please read the [FAQ](https://www.circl.lu/doc/misp/faq/) before opening an issue.
        We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

        Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.


        If you would like to ask for support, please fill the template bellow:
  - type: textarea
    id: support-questions
    attributes:
      label: Support Questions
    validations:
      required: true
  - type: input
    id: misp-version
    attributes:
      label: MISP version
      description: What version of MISP are you running?
      placeholder: "2.4.151"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Ubuntu, RedHat, CentOS ..."
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System version
      placeholder: "20.04"
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP version
      placeholder: "7.0, 7.1, 7.4 ..."
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you seeing the problem on?
      placeholder: "Firefox, Chrome, Safari ..."
  - type: input
    id: browser-version
    attributes:
      label: Browser version
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: extra-attachments
    attributes:
      label: Extra attachments
      description: Please add any other relevant attachments such as screenshots, log files, etc. here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/MISP/MISP/blob/2.4/code_of_conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
